default_platform(:ios)

platform :ios do
  before_all do
    @is_CI = ENV["IS_CI"]
    # Fastlane
    @fastlane_match_auth_token = ENV["FASTLANE_MATCH_AUTH_TOKEN"]
    @fastlane_match_password = ENV["FASTLANE_MATCH_PASSWORD"]
    # AppStore
    @app_store_connect_api_key_id = ENV["APP_STORE_CONNECT_API_KEY_ID"]
    @app_store_connect_api_issuer_id = ENV["APP_STORE_CONNECT_API_ISSUER_ID"]
    @app_store_connect_api_p8_key = ENV["APP_STORE_CONNECT_API_P8_KEY"]
    # TestFlight
    @test_flight_beta_feedback_email = ENV["TEST_FLIGHT_BETA_FEEDBACK_EMAIL"]
  end

  # Code Signing

  desc "Sync CodeSigning"
  lane :sync_codesigning do
    sync_code_signing(
      type: "development",
      force_for_new_devices: true,
      readonly: is_CI
    )
    sync_code_signing(
      type: "appstore",
      readonly: is_CI
    )
  end

  # Run & Unit Tests

  desc "Run UnitTests"
  lane :run_unit_tests do
    run_tests(
      scheme: "EmojiShoppingList-UnitTests",
      devices: ["iPhone 8", "iPhone 14 Pro"],
      result_bundle: true,
      derived_data_path: "unit_tests",
      output_directory: "unit_tests",
    )
  end

  # TestFlight

  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci
    sync_codesigning
    increment_build_number(
      xcodeproj: "EmojiShoppingList.xcodeproj"
    )
    build_app(
      scheme: "EmojiShoppingList"
    )
  
    api_key = app_store_connect_api_key(
      is_key_content_base64: true,
      key_id: @app_store_connect_api_key_id,
      issuer_id: @app_store_connect_api_issuer_id,
      key_content: @app_store_connect_api_p8_key,
      in_house: false,
    )

    upload_to_testflight(
      beta_app_feedback_email: @test_flight_beta_feedback_email,
      api_key: api_key,
      skip_waiting_for_build_processing: true
    )
  end
end