# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Run UnitTests"
  lane :run_unit_tests do
    run_tests(
      scheme: "EmojiShoppingList-UnitTests",
      devices: ["iPhone 8", "iPhone 14 Pro"],
      result_bundle: true,
      derived_data_path: "unit_tests",
      output_directory: "unit_tests",
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(
      xcodeproj: "EmojiShoppingList.xcodeproj"
    )
    build_app(
      scheme: "EmojiShoppingList"
    )
    upload_to_testflight
  end
end
