name: Build & Test

on:
  push:
    branches:
    - develop
  workflow_dispatch:

jobs:
  Develop:
    name: Build & Test
    runs-on: macos-12
    env: 
      IS_CI: true
      # Fastlane
      FASTLANE_MATCH_AUTH_TOKEN: ${{ secrets.FASTLANE_MATCH_AUTH_TOKEN }}
      FASTLANE_MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSWORD }}
      # AppStore
      APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
      APP_STORE_CONNECT_API_P8_KEY: ${{ secrets.APP_STORE_CONNECT_API_P8_KEY }}
      # TestFlight
      TEST_FLIGHT_BETA_FEEDBACK_EMAIL: ${{ secrets.TEST_FLIGHT_BETA_FEEDBACK_EMAIL }}

    steps:
      - name: Switch to latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: latest

      - name: Checkout
        if: success()
        timeout-minutes: 5
        uses: actions/checkout@v1

      - name: Install Dependencies
        if: success()
        run: bundle install

      # - name: Run Unit Tests
      #   if: success()
      #   uses: maierj/fastlane-action@v1.4.0
      #   with:
      #     lane: run_unit_tests

      - name: Upload to TestFlight
        if: success()
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: beta

      - name: Create Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: unit_tests/EmojiShoppingList-UnitTests.xcresult