name: Build & Tests

on:
  push:
    branches:
    - development
  workflow_dispatch:

jobs:
  Develop:
    runs-on: macos-12

    steps:
      - name: Switch to latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: latest

      - name: Checkout
        if: success()
        timeout-minutes: 5
        uses: actions/checkout@v1

      - name: Install Dependencies
        if: success()
        run: bundle install

      - name: Run Unit Tests
        if: success()
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: run_unit_tests

      - name: Create Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: unit_tests/EmojiShoppingList-UnitTests.xcresult