name: Build & Unit Tests

on:
  push:
    branches:
    - develop
  workflow_dispatch:

jobs:
  Develop:
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: latest

      - name: Checkout 
        timeout-minutes: 5
        uses: actions/checkout@v1

      - name: Install Dependencies
        if: success()
        run: bundle install
        
      - name: Build and Unit Tests
        if: success()
        run: bundle exec fastlane scan --scheme "EmojiShoppingList" --device "iPhone 13 Pro" --clean