name: Build & Unit Tests

on:
  push:
    branches:
    - develop
  workflow_dispatch:

jobs:
  Develop:
    name: Build & Unit Tests
    runs-on: macos-12

    steps:
      - name: Switch to latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
         xcode-version: latest

      - name: Checkout
        if: success()
        timeout-minutes: 5
        uses: actions/checkout@v1

      - name: Create SSH Key
        if: success()
        uses: shimataro/ssh-key-action@v2.0.0
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOST }}
          config: |
            Host github
              AddKeysToAgent yes
              UseKeychain yes
              IdentityFile ~/.ssh/id_rsa

      - name: Configure SSH Key
        if: success()
        run: |
          ssh-add -K ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Install Dependencies
        if: success()
        run: bundle install

      - name: Run Unit Tests
        if: success()
        uses: maierj/fastlane-action@v1.4.0
        with:
          lane: run_unit_tests

      - name: Create Test Results
        uses: kishikawakatsumi/xcresulttool@v1
        if: success() || failure()
        with:
          path: unit_tests/EmojiShoppingList-UnitTests.xcresult